---
title: "Untitled"
output: html_document
---


```{r}
ccdata<-read.csv("UCI_Credit_Card.csv")
```



```{r}
install.packages('shiny')
library(shiny)
library(ggplot2)
```
```{r}

library(rsconnect)
```

```{r}
rsconnect::setAccountInfo(name='882612jerry',
			  token='ED973943F439455F4D053BA170F5336C',
			  secret='tnesc4ideSVDp/UH/frm7l/zsTRoq9glXauo7oAw')

```

```{r}
library(rsconnect)
rsconnect::deployApp('path/to/your/app')

```

```{r}
library(shiny)
library(ggplot2)

shinyServer(function(input, output) {

  dataset <- reactive({
    diamonds[sample(nrow(diamonds), input$sampleSize),]
  })

  output$plot <- renderPlot({

    p <- ggplot(dataset(), aes_string(x=input$x, y=input$y)) + geom_point()

    if (input$color != 'None')
      p <- p + aes_string(color=input$color)

    facets <- paste(input$facet_row, '~', input$facet_col)
    if (facets != '. ~ .')
      p <- p + facet_grid(facets)

    if (input$jitter)
      p <- p + geom_jitter()
    if (input$smooth)
      p <- p + geom_smooth()

    print(p)

  }, height=700)

}
)
```





```{r}
library(shiny)
library(ggplot2)

dataset <- diamonds

shinyUI(fluidPage(

  titlePanel("Diamonds Explorer"),

  sidebarPanel(

    sliderInput('sampleSize', 'Sample Size', min=1, max=nrow(dataset),
                value=min(1000, nrow(dataset)), step=500, round=0),

    selectInput('x', 'X', names(dataset)),
    selectInput('y', 'Y', names(dataset), names(dataset)[[2]]),
    selectInput('color', 'Color', c('None', names(dataset))),

    checkboxInput('jitter', 'Jitter'),
    checkboxInput('smooth', 'Smooth'),

    selectInput('facet_row', 'Facet Row', c(None='.', names(dataset))),
    selectInput('facet_col', 'Facet Column', c(None='.', names(dataset)))
  ),

  mainPanel(
    plotOutput('plot')
  )
)
)

```
```{r}
library(shiny)
runApp()
```

```{r}
library(rsconnect)
deployApp()
```

```{r}
rsconnect::configureApp("APPNAME", size="small")
```

```{r}
 library(shiny)
  shinyUI(fluidPage(
     titlePanel("大家好")
  ))
```

```{r}
 library(shiny)
  shinyUI(fluidPage(
    titlePanel("大家好"),
    titlePanel("大家好"),
    titlePanel("大家好")
  ))
```

```{r}
  radioButtons("radio", label = "Choices", choices = list("Choice 1" = 1, "Choice 2" = 2))
```

```{r}
 sliderInput("slider1", label = "Slider", min = 0, max = 100, value = 50)
```

```{r}
  library(shiny)
  shinyUI(fluidPage(
    titlePanel("大家好"),
    sidebarLayout(
      sidebarPanel(
        radioButtons("radio", label = "Choices", choices = list("Choice 1" = 1, "Choice 2" = 2)),
        sliderInput("slider1", label = "Slider", min = 0, max = 100, value = 50)
      ),
      mainPanel("逮給厚，哇喜逮頑歐郎")
    )
  ))
```

```{r}
 shinyServer(function(input, output) {
    output$distPlot <- renderPlot({
      x <- faithful[, 2] # Old Faithful Geyser data
      bins <- seq(min(x), max(x), length.out = 10)
      hist(x, breaks = bins, col = 'blue', border = 'white')
    })
  })

```


```{r}
mainPanel(plotOutput("distPlot"))
```

```{r}
  sliderInput("slider1", label = "Slider", min = 0, max = 100, value = 50)
```

```{r}
bins <- seq(min(x), max(x), length.out = input$slider + 1)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

